name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          IMAGE_TAG=maeriley/nginx_testapp:${TIMESTAMP}
          docker pull nginx:latest
          docker build -t ${IMAGE_TAG} --build-arg CACHEBUST=$(date +%s) .
          docker push ${IMAGE_TAG}
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_ACI: 1
