name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker pull nginx:latest
          docker build -t maeriley/nginx_testapp:1.0.0.1 --build-arg CACHEBUST=$(date +%s) .
          docker push maeriley/nginx_testapp:1.0.0.1
        env:
          DOCKER_BUILDKIT: 1
          DOCKER_CLI_ACI: 1
